server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true